const VERSION='2026-08-19';
const SCOPES=['MERCHANT_PROFILE_READ','ITEMS_READ','ORDERS_READ','PAYMENTS_READ'];
const SANDBOX_APP='sandbox-sq0idb-EnUpCW6_2pJQKHmw9b2TCw';
const enc=new TextEncoder(),dec=new TextDecoder();
const json=(x,s=200,h={})=>new Response(JSON.stringify(x),{status:s,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...h}});
const cookieId=r=>(r.headers.get('cookie')||'').match(/(?:^|;\s*)p2p_workspace=([a-f0-9]{64})(?:;|$)/)?.[1]||null;
async function tables(env){await env.DB.prepare('CREATE TABLE IF NOT EXISTS p2p_square_oauth_states (state TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,expires_at TEXT NOT NULL)').run();await env.DB.prepare('CREATE TABLE IF NOT EXISTS p2p_square_connections (workspace_id TEXT PRIMARY KEY,merchant_id TEXT,access_token TEXT NOT NULL,refresh_token TEXT,expires_at TEXT,environment TEXT NOT NULL,last_sync_at TEXT,snapshot TEXT,updated_at TEXT NOT NULL)').run();}
async function key(env){if(!env.SQUARE_APPLICATION_SECRET)throw new Error('Square application secret is not configured.');const raw=await crypto.subtle.digest('SHA-256',enc.encode('price2plate-square-token:'+env.SQUARE_APPLICATION_SECRET));return crypto.subtle.importKey('raw',raw,{name:'AES-GCM'},false,['encrypt','decrypt']);}
async function seal(env,value){if(!value)return null;const iv=crypto.getRandomValues(new Uint8Array(12));const out=await crypto.subtle.encrypt({name:'AES-GCM',iv},await key(env),enc.encode(value));const bytes=new Uint8Array(iv.byteLength+out.byteLength);bytes.set(iv);bytes.set(new Uint8Array(out),iv.byteLength);return btoa(String.fromCharCode(...bytes));}
async function open(env,value){if(!value)return null;const bytes=Uint8Array.from(atob(value),c=>c.charCodeAt(0)),iv=bytes.slice(0,12),data=bytes.slice(12);return dec.decode(await crypto.subtle.decrypt({name:'AES-GCM',iv},await key(env),data));}
function config(env){const sandbox=(env.SQUARE_ENVIRONMENT||'sandbox')!=='production';return{sandbox,app:env.SQUARE_APPLICATION_ID||SANDBOX_APP,oauth:sandbox?'https://connect.squareupsandbox.com/oauth2':'https://connect.squareup.com/oauth2',api:sandbox?'https://connect.squareupsandbox.com/v2':'https://connect.squareup.com/v2'};}
async function tokenRequest(env,body){const c=config(env);const payload={...body,client_id:c.app,client_secret:env.SQUARE_APPLICATION_SECRET};const r=await fetch(c.oauth+'/token',{method:'POST',headers:{'Content-Type':'application/json','Square-Version':VERSION},body:JSON.stringify(payload)});let j={};try{j=await r.json();}catch{}if(!r.ok){const detail=j.errors?.map(e=>e.detail||e.code).filter(Boolean).join(' | ')||j.error_description||j.error||('Square token exchange failed ('+r.status+').');throw new Error(detail);}return j;}
async function connection(env,id){return env.DB.prepare('SELECT * FROM p2p_square_connections WHERE workspace_id=?').bind(id).first();}
async function access(env,row){if(row.expires_at&&Date.parse(row.expires_at)-Date.now()<300000&&row.refresh_token){const t=await tokenRequest(env,{grant_type:'refresh_token',refresh_token:await open(env,row.refresh_token)});await env.DB.prepare('UPDATE p2p_square_connections SET access_token=?,refresh_token=?,expires_at=?,updated_at=? WHERE workspace_id=?').bind(await seal(env,t.access_token),await seal(env,t.refresh_token||await open(env,row.refresh_token)),t.expires_at||null,new Date().toISOString(),row.workspace_id).run();row=await connection(env,row.workspace_id);}return await open(env,row.access_token);}
async function sq(env,row,path,opts={}){const c=config(env),t=await access(env,row);const r=await fetch(c.api+path,{...opts,headers:{Authorization:'Bearer '+t,'Square-Version':VERSION,'Content-Type':'application/json',...(opts.headers||{})}});const j=await r.json();if(!r.ok)throw new Error(j.errors?.[0]?.detail||('Square request failed: '+r.status));return j;}
async function sync(env,row){const loc=await sq(env,row,'/locations');const ids=(loc.locations||[]).filter(x=>x.status!=='INACTIVE').map(x=>x.id);let objects=[],cursor='';do{const q=new URLSearchParams({types:'ITEM,CATEGORY,TAX,DISCOUNT,MODIFIER_LIST'});if(cursor)q.set('cursor',cursor);const page=await sq(env,row,'/catalog/list?'+q);objects.push(...(page.objects||[]));cursor=page.cursor||'';}while(cursor&&objects.length<3000);const start=new Date(Date.now()-30*86400000).toISOString();let orders=[];if(ids.length){let oc='';do{const body={location_ids:ids,query:{filter:{date_time_filter:{closed_at:{start_at:start}}},sort:{sort_field:'CLOSED_AT',sort_order:'DESC'}},limit:500};if(oc)body.cursor=oc;const page=await sq(env,row,'/orders/search',{method:'POST',body:JSON.stringify(body)});orders.push(...(page.orders||[]));oc=page.cursor||'';}while(oc&&orders.length<5000);}const itemSales=new Map();let gross=0;for(const o of orders){if(!['COMPLETED','OPEN'].includes(o.state))continue;gross+=Number(o.total_money?.amount||0);for(const li of o.line_items||[]){const name=li.name||li.variation_name||'Unnamed item',qty=Number(li.quantity||0),amount=Number(li.total_money?.amount||li.gross_sales_money?.amount||0),v=itemSales.get(name)||{name,quantity:0,sales_cents:0};v.quantity+=qty;v.sales_cents+=amount;itemSales.set(name,v);}}
const snap={locations:(loc.locations||[]).map(x=>({id:x.id,name:x.name,status:x.status,currency:x.currency})),catalog_items:objects.filter(x=>x.type==='ITEM').length,orders_30d:orders.length,gross_sales_30d_cents:gross,top_items:[...itemSales.values()].sort((a,b)=>b.sales_cents-a.sales_cents).slice(0,20)};await env.DB.prepare('UPDATE p2p_square_connections SET snapshot=?,last_sync_at=?,updated_at=? WHERE workspace_id=?').bind(JSON.stringify(snap),new Date().toISOString(),new Date().toISOString(),row.workspace_id).run();return snap;}
export async function handleSquare(request,env){const url=new URL(request.url);if(!url.pathname.startsWith('/api/square/'))return null;if(!env.DB)return json({error:'Square storage is unavailable.'},503);await tables(env);const c=config(env);try{
if(url.pathname==='/api/square/callback'){const state=url.searchParams.get('state'),code=url.searchParams.get('code'),err=url.searchParams.get('error');if(err)return Response.redirect(url.origin+'/?square=denied',302);const s=state&&await env.DB.prepare('SELECT * FROM p2p_square_oauth_states WHERE state=?').bind(state).first();if(!s||Date.parse(s.expires_at)<Date.now()||!code)return Response.redirect(url.origin+'/?square=failed',302);const t=await tokenRequest(env,{grant_type:'authorization_code',code});await env.DB.prepare('INSERT INTO p2p_square_connections (workspace_id,merchant_id,access_token,refresh_token,expires_at,environment,updated_at) VALUES (?,?,?,?,?,?,?) ON CONFLICT(workspace_id) DO UPDATE SET merchant_id=excluded.merchant_id,access_token=excluded.access_token,refresh_token=excluded.refresh_token,expires_at=excluded.expires_at,environment=excluded.environment,updated_at=excluded.updated_at').bind(s.workspace_id,t.merchant_id||null,await seal(env,t.access_token),await seal(env,t.refresh_token||null),t.expires_at||null,c.sandbox?'sandbox':'production',new Date().toISOString()).run();await env.DB.prepare('DELETE FROM p2p_square_oauth_states WHERE state=?').bind(state).run();return Response.redirect(url.origin+'/?square=connected#square-pos',302);}
const id=cookieId(request);if(!id)return json({error:'Open your Price 2 Plate workspace first.'},401);
if(url.pathname==='/api/square/status'&&request.method==='GET'){const row=await connection(env,id);if(!row)return json({connected:false,environment:c.sandbox?'sandbox':'production',application_configured:Boolean(env.SQUARE_APPLICATION_SECRET)});return json({connected:true,environment:row.environment,merchant_id:row.merchant_id,last_sync_at:row.last_sync_at,snapshot:row.snapshot?JSON.parse(row.snapshot):null,application_configured:true});}
if(url.pathname==='/api/square/connect'&&request.method==='POST'){if(!env.SQUARE_APPLICATION_SECRET)return json({error:'Square application secret must be added to Cloudflare first.'},503);const state=Array.from(crypto.getRandomValues(new Uint8Array(24)),x=>x.toString(16).padStart(2,'0')).join('');await env.DB.prepare('INSERT INTO p2p_square_oauth_states (state,workspace_id,expires_at) VALUES (?,?,?)').bind(state,id,new Date(Date.now()+600000).toISOString()).run();const q=new URLSearchParams({client_id:c.app,scope:SCOPES.join(' '),state});if(!c.sandbox)q.set('session','false');return json({url:c.oauth+'/authorize?'+q.toString(),scopes:SCOPES,environment:c.sandbox?'sandbox':'production'});}
if(url.pathname==='/api/square/sync'&&request.method==='POST'){const row=await connection(env,id);if(!row)return json({error:'Connect Square first.'},409);return json({ok:true,snapshot:await sync(env,row)});}
if(url.pathname==='/api/square/disconnect'&&request.method==='POST'){const row=await connection(env,id);if(row){try{const t=await open(env,row.access_token);await fetch(c.oauth+'/revoke',{method:'POST',headers:{Authorization:'Client '+env.SQUARE_APPLICATION_SECRET,'Square-Version':VERSION,'Content-Type':'application/json'},body:JSON.stringify({client_id:c.app,access_token:t,revoke_only_access_token:true})});}catch{}await env.DB.prepare('DELETE FROM p2p_square_connections WHERE workspace_id=?').bind(id).run();}return json({ok:true});}
return json({error:'Unknown Square route.'},404);
}catch(e){return json({error:e?.message||'Square integration failed.'},500);}}
